info:
  project:
    name: my-video-notify

spring:
  application.name: my-video-notify
  config:
    import: optional:file:.env[.properties]
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      fail_on_empty_beans: false
      write_dates_as_timestamps: false
    property-naming-strategy: SNAKE_CASE

third-party:
  my-video-function:
    api-key: "SUA_CHAVE_API"
    url: "https://api.myvideofunction.com"
    timeout: 5000

nats:
  spring:
    server: ${NATS_SERVERS:nats://localhost:4222}

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
    tagsSorter: alpha
    operationsSorter: alpha
    writer-with-order-by-keys: true
  path: /api/v1/swagger-ui/index.html

messaging:
  topics:
    video-completed: video.completed
    video-error: video.error
  group: video-manager

logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL:DEBUG}
    io:
      github:
        soat7:
          myvideonotify: ${LOG_LEVEL:DEBUG}
